services:
  panelio:
    build: .
    container_name: panelio
    restart: unless-stopped
    ports:
      - "3011:3000"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "localhost"
      PANELIO_ADMIN_PASSWORD: "changeme"
      PUID: "1000"
      PGID: "1000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
